
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.64
distribution_type: module
version: 0.01
name: Module-Collection
author: Adam Kennedy <adamk@cpan.org>
license: perl
build_requires: 
  Test::More: 0.42
requires: 
  Module::Inspector: 0.02
  File::Find::Rule: 0
  perl: 5.005
  Params::Util: 0.10
  Module::Math::Depends: 0.01
  Carp: 0
abstract: Examine a group of Perl distributions
